// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyGCm0pMvqQn2oII80OG7KkMVFihWBHBo',
    appId: '1:662263115646:web:f11bd8cc934036f8428d2f',
    messagingSenderId: '662263115646',
    projectId: 'hotel-b4e73',
    authDomain: 'hotel-b4e73.firebaseapp.com',
    storageBucket: 'hotel-b4e73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroM0-Ik24bU9CvQlUH53AotlmsJ-4vwA',
    appId: '1:662263115646:android:8e2df235089af109428d2f',
    messagingSenderId: '662263115646',
    projectId: 'hotel-b4e73',
    storageBucket: 'hotel-b4e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYXuBUeeByGbKghKONeXeOVcDiafTfJo',
    appId: '1:662263115646:ios:85cfe052d6ddc97f428d2f',
    messagingSenderId: '662263115646',
    projectId: 'hotel-b4e73',
    storageBucket: 'hotel-b4e73.appspot.com',
    iosBundleId: 'com.example.serenadepalace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYXuBUeeByGbKghKONeXeOVcDiafTfJo',
    appId: '1:662263115646:ios:85cfe052d6ddc97f428d2f',
    messagingSenderId: '662263115646',
    projectId: 'hotel-b4e73',
    storageBucket: 'hotel-b4e73.appspot.com',
    iosBundleId: 'com.example.serenadepalace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyGCm0pMvqQn2oII80OG7KkMVFihWBHBo',
    appId: '1:662263115646:web:25800acf2010c7bd428d2f',
    messagingSenderId: '662263115646',
    projectId: 'hotel-b4e73',
    authDomain: 'hotel-b4e73.firebaseapp.com',
    storageBucket: 'hotel-b4e73.appspot.com',
  );
}
